language: c
dist: xenial
osx_image: xcode10.2
os:
  - linux
  - osx
compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - ninja-build
      - libfuse-dev
  homebrew:
    packages:
      - meson
      - osxfuse

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install meson; fi

script:
 - meson build
 - cd build
 - ninja
