language: c
dist: xenial
osx_image: xcode10.1
os:
  - linux
  - osx
compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build
      - libfuse-dev
  homebrew:
    packages:
      - meson
      - osxfuse
    update: true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install meson; fi

script:
 - meson build
 - cd build
 - ninja
