language: c
dist: xenial
osx_image: xcode10.2
os:
  - linux
  - osx
compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
      - meson
      - libfuse-dev
  homebrew:
    packages:
      - meson
      - osxfuse

script:
 - meson build
 - cd build
 - ninja
