language: c
dist: xenial
os:
  - linux
  - osx
compiler:
 - gcc
 - clang

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install meson osxfuse; fi
addons:
  apt:
    packages:
      - meson
      - libfuse-dev

script:
 - meson build
 - cd build
 - ninja
