language: c
os:
  - linux
  - osx

compiler:
 - gcc
 - clang

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install meson; fi
addons:
  apt:
    packages:
      - meson

script:
 - meson setup build
 - cd build
 - ninja
