language: c
dist: xenial
osx_image: xcode10.1
os:
  - linux
  - osx
compiler:
 - gcc
 - clang

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - ninja-build
      - libfuse-dev
      - libelf-dev
  homebrew:
    packages:
      - meson
    casks:
      - osxfuse
    update: true

before_script:
  - '[[ ! "$TRAVIS_OS_NAME" == "linux" ]] || pip3 install meson'

script:
 - meson build
 - cd build
 - ninja
 - ls -R subprojects
 - '[[ ! "$TRAVIS_OS_NAME" == "osx" ]] || [[ -e subprojects/frontend-darwin/fscompat.kext ]]'
 - '[[ ! "$TRAVIS_OS_NAME" == "linux" ]] || [[ -e subprojects/frontend-linux/fscompat.ko ]]'
 - test -e subprojects/frontend-fuse/fscompat-fuse-fat
